# Utilizar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el script de reporte y los archivos necesarios
COPY populate_db.py .
COPY WorldCups.csv .
COPY reporte.py .

# Copiar el archivo de requisitos primero para aprovechar el caché de Docker
COPY requirements.txt .

# Instalar dependencias
RUN pip install -r requirements.txt

# Comando por defecto para ejecutar el script de reporte
CMD ["python", "populate_db.py", "reporte.py"]
