version: '3.8'

services:
  db:
    image: postgres:12.7
    container_name: postgres_db
    environment:
      POSTGRES_DB: world_cup_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  populate_db:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_DB=world_cup_data
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
    volumes:
      - ./populate_db.py:/app/populate_db.py
      - ./WorldCups.csv:/app/WorldCups.csv

volumes:
  db_data:
